kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: ukf
data:
  default.conf: |
    server {
      listen 80 default_server;
      index index.php index.html;
      server_name _;
      root /var/www/html;
      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }
      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        include fastcgi_params;
      }
    }
