kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: ukf
spec:
  ports:
    - name: http
      protocol: TCP
      port: 81
      targetPort: 80
      nodePort: 31534
  selector:
    app: nginx
  type: NodePort
  sessionAffinity: None
